import assert from 'node:assert/strict';
import mysql from 'mysql2/promise';
const base='http://127.0.0.1:3000/api';
function client(){let cookie='';return async(path,method='GET',body,status=200)=>{const r=await fetch(base+path,{method,headers:{Origin:'http://test.local',Cookie:cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const d=await r.json();assert.equal(r.status,status,`${method} ${path} ${JSON.stringify(d)}`);return d;};}
const admin=client(),shop=client(),guest=client(),sales=client(),anon=client();
await admin('/login','POST',{username:'admin',password:'TestChanged123!'});
await shop('/login','POST',{username:'shop_one',password:'ShopChanged123!'});
await sales('/login','POST',{username:'seller_a',password:'SellerChanged123!'});
await shop('/categories','POST',{name:'越权',nameEn:'Denied',sortOrder:1},403);
await sales('/categories','POST',{name:'越权',nameEn:'Denied',sortOrder:1},403);
await admin('/categories','POST',{name:'测试',nameEn:'Test',sortOrder:-1},400);
const category=await admin('/categories','POST',{name:'城市活动',nameEn:'City events',sortOrder:1},201);
await admin('/categories/'+category.id,'PUT',{name:'城市体验',nameEn:'City experiences',sortOrder:0,version:1});
await admin('/categories/'+category.id,'PUT',{name:'旧数据',nameEn:'Stale',sortOrder:1,version:1},409);
const publicCategories=(await anon('/public/adverts')).categories;
assert.equal(publicCategories[0].id,category.id);assert.equal(publicCategories[0].nameEn,'City experiences');
const unused=await admin('/categories','POST',{name:'未使用',nameEn:'Unused',sortOrder:10},201);
await admin('/categories/'+unused.id,'DELETE',{version:1});
const current=(await shop('/market')).adverts[0];
const advert={...current,category:category.id,status:'pending',expiresOn:'2099-12-31'};
await shop('/adverts','POST',{...advert,category:unused.id},400);
const ad=await shop('/adverts','POST',advert,201);
await admin('/adverts/'+ad.id+'/review','POST',{status:'published',reviewNote:'',pinned:false,version:1});
await admin('/categories/'+category.id,'DELETE',{version:2},409);
await admin('/categories/'+category.id,'PUT',{name:'夜间体验',nameEn:'Night experiences',sortOrder:0,version:2});
assert.equal((await anon('/public/adverts/'+ad.id)).categoryNameEn,'Night experiences');
await guest('/register','POST',{username:'commerce_guest',name:'销售关联测试客人',phone:'13811111111',password:'GuestPassword123!'},201);
await guest('/login','POST',{username:'commerce_guest',password:'GuestPassword123!'});
await guest('/categories','GET',undefined,403);await shop('/sale-options','GET',undefined,403);
const customer=(await admin('/data')).customers.find(c=>c.name==='销售关联测试客人');
const payload={customerId:customer.id,item:'实际成交',cents:12000,date:new Date().toISOString().slice(0,10)};
const book=await guest('/reservations','POST',{advertId:ad.id,requestedAt:new Date(Date.now()+86400000).toISOString(),message:'测试预约'},201);
await admin('/sales','POST',{...payload,reservationId:book.id,reservationVersion:1},409);
await shop('/reservations/'+book.id,'PATCH',{status:'confirmed',reply:'欢迎',version:1});
await shop('/sales','POST',{...payload,reservationId:book.id,reservationVersion:2},403);
await guest('/sales','POST',payload,403);
await sales('/sales','POST',{...payload,reservationId:book.id,reservationVersion:2},404);
const wrongShop=(await admin('/market')).shops.find(s=>s.id!==current.shopId);
await admin('/sales','POST',{...payload,shopId:wrongShop.id,advertId:ad.id},400);
await admin('/sales','POST',{...payload,reservationId:book.id,reservationVersion:1},409);
const seller=(await admin('/users')).find(u=>u.username==='seller_a');
await admin('/customers/'+customer.id,'PUT',{...customer,ownerId:seller.id,version:customer.version});
const converted=await sales('/sales','POST',{...payload,reservationId:book.id,reservationVersion:2},201);
await sales('/sales','POST',{...payload,reservationId:book.id,reservationVersion:2},409);
let record=(await sales('/data')).sales.find(s=>s.id===converted.id);
assert.equal(record.shopId,current.shopId);assert.equal(record.advertId,ad.id);assert.equal(record.reservationId,book.id);
assert.equal((await sales('/reservations')).find(r=>r.id===book.id).saleId,converted.id);
assert.equal((await guest('/reservations')).find(r=>r.id===book.id).status,'confirmed','conversion does not complete a booking');
await sales('/sales/'+converted.id,'PUT',{...payload,shopId:wrongShop.id,version:1},400);
await sales('/sales/'+converted.id,'PUT',{...payload,item:'更正项目',cents:15000,version:1});
assert.equal((await sales('/data')).sales.find(s=>s.id===converted.id).reservationId,book.id);
const manual=await sales('/sales','POST',{...payload,shopId:current.shopId,advertId:ad.id},201);
const unlinked=await sales('/sales','POST',payload,201);
assert.equal((await sales('/data')).sales.find(s=>s.id===unlinked.id).shopId,null);
await shop('/reservations/'+book.id,'PATCH',{status:'completed',reply:'完成',version:2});
const cancelled=await guest('/reservations','POST',{advertId:ad.id,requestedAt:new Date(Date.now()+86400000).toISOString(),message:'取消测试'},201);
await guest('/reservations/'+cancelled.id,'PATCH',{status:'cancelled',reply:'',version:1});
await sales('/sales','POST',{...payload,reservationId:cancelled.id,reservationVersion:2},409);
// Remove only this test's customer records so the existing restart assertion remains valid.
const db=await mysql.createConnection({host:'db',user:'neon',password:'TestDatabase123',database:'neon'});
await db.execute('DELETE FROM sales WHERE customer_id=?',[customer.id]);
await db.execute('DELETE FROM reservations WHERE id IN (?,?)',[book.id,cancelled.id]);
await db.execute('DELETE FROM customer_accounts WHERE customer_id=?',[customer.id]);
await db.execute('DELETE FROM customers WHERE id=?',[customer.id]);
await db.end();
console.log('PASS: category permissions, rename/order/delete, public bilingual sync, sale ownership, optional links, booking conversion, duplicate prevention and cancelled booking rejection');
