import assert from 'node:assert/strict';
import sharp from 'sharp';
const base='http://127.0.0.1:3000/api',origin='http://test.local',merchantOrigin='http://merchant.test';
function client(source=origin){let cookie='';return async(path,method='GET',body,status=200)=>{const r=await fetch(base+path,{method,headers:{Origin:source,Cookie:cookie,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const d=await r.json();assert.equal(r.status,status,`${method} ${path}: ${JSON.stringify(d)}`);return d;};}
const admin=client(),shop=client(merchantOrigin),other=client(merchantOrigin),unicodeShop=client(merchantOrigin),guest=client(),anon=client();
await admin('/login','POST',{username:'admin',password:'TestChanged123!'});
for(const [c,n,name] of [[shop,'shop_one','店主甲'],[other,'shop_two','店主乙'],[unicodeShop,'店铺1','中文账号测试']])await c('/merchant-register','POST',{username:n,name,password:'ShopInitial123!'},201);
await shop('/login','POST',{username:'shop_one',password:'ShopInitial123!'},403);
const merchantUsers=await admin('/merchant-users');
assert.equal(merchantUsers.length,3);assert.ok(merchantUsers.every(u=>u.merchantStatus==='pending'&&!u.enabled));
assert.equal((await admin('/users')).some(u=>u.role==='shop'),false,'merchant accounts are separate from platform accounts');
for(const u of merchantUsers)await admin('/merchant-users/'+u.id,'PATCH',{name:u.name,state:'approved'});
await client()('/login','POST',{username:'shop_one',password:'ShopInitial123!'},403);
await client(merchantOrigin)('/login','POST',{username:'admin',password:'TestChanged123!'},403);
for(const [c,n] of [[shop,'shop_one'],[other,'shop_two'],[unicodeShop,'店铺1']]){await c('/login','POST',{username:n,password:'ShopInitial123!'});await c('/password','POST',{oldPassword:'ShopInitial123!',newPassword:'ShopChanged123!'});await c('/login','POST',{username:n,password:'ShopChanged123!'});}
await shop('/data','GET',undefined,403);
const info={name:'测试店铺',nameEn:'Test shop',description:'店铺介绍',descriptionEn:'About us',phone:'123456',wechat:'test',address:'测试地址'};
const administrator=(await admin('/me')).user;
await admin('/shops','POST',{...info,ownerId:administrator.id,enabled:true},400);
const s=await shop('/shops','POST',info,201);await shop('/shops','POST',info,409);
await other('/shops/'+s.id,'PUT',{...info,version:1},404);
const s2=await other('/shops','POST',{...info,name:'其他店铺'},201);
const image='data:image/jpeg;base64,'+(await sharp({create:{width:64,height:64,channels:3,background:'#dd2277'}}).jpeg().toBuffer()).toString('base64');
await shop('/media','POST',{purpose:'avatar',data:image},403);
await shop('/media','POST',{purpose:'advert',data:'data:image/jpeg;base64,AAAA'},400);
const m=await shop('/media','POST',{purpose:'advert',data:image},201);
const advert={shopId:s.id,title:'测试业务',titleEn:'Test experience',body:'中文内容',bodyEn:'English content',category:'services',images:[m.id],status:'pending',expiresOn:'2099-12-31'};
await shop('/adverts','POST',{...advert,titleEn:''},400);
const a=await shop('/adverts','POST',advert,201);
assert.equal((await anon('/public/adverts')).items.length,0,'pending is private');
await anon('/public/media/'+m.id,'GET',undefined,404);
await other('/adverts/'+a.id,'PUT',{...advert,shopId:s2.id,version:1},404);
await shop('/adverts/'+a.id+'/review','POST',{status:'published',reviewNote:'',version:1},403);
await admin('/adverts/'+a.id+'/review','POST',{status:'published',reviewNote:'',pinned:true,version:1});
assert.equal((await anon('/public/adverts?q=experience')).items.length,1);
assert.equal((await anon('/public/adverts?category=food')).items.length,0);
assert.equal((await anon('/public/adverts/'+a.id)).titleEn,'Test experience');
assert.equal((await fetch(base+'/public/media/'+m.id)).headers.get('content-type'),'image/jpeg');
await guest('/register','POST',{username:'guest_one',name:'注册客人',phone:'13800000000',password:'GuestPassword123!'},201);
await guest('/login','POST',{username:'guest_one',password:'GuestPassword123!'});
const guestProfile=(await guest('/me')).user;assert.ok(guestProfile.customerId);
const guestAvatar=await guest('/media','POST',{purpose:'avatar',data:image},201);
await guest('/media','POST',{purpose:'advert',data:image},403);
await guest('/customers/'+guestProfile.customerId+'/avatar','PUT',{mediaId:guestAvatar.id,version:guestProfile.customerVersion});
assert.equal((await guest('/me')).user.avatarId,guestAvatar.id);
assert.ok((await admin('/data')).customers.some(c=>c.name==='注册客人'));
await guest('/market','GET',undefined,403);await guest('/data','GET',undefined,403);
const booking={advertId:a.id,requestedAt:new Date(Date.now()+86400000).toISOString(),message:'两位，想咨询时间。'};
const b=await guest('/reservations','POST',booking,201);await guest('/reservations','POST',booking,409);
assert.equal((await other('/reservations')).length,0);
await other('/reservations/'+b.id,'PATCH',{status:'confirmed',reply:'',version:1},404);
await shop('/reservations/'+b.id,'PATCH',{status:'confirmed',reply:'欢迎，时间已确认。',version:1});
assert.equal((await guest('/reservations'))[0].reply,'欢迎，时间已确认。');
await guest('/reservations/'+b.id,'PATCH',{status:'completed',reply:'',version:2},409);
await guest('/reservations/'+b.id,'PATCH',{status:'cancelled',reply:'',version:2});
await shop('/adverts/'+a.id,'PUT',{...advert,bodyEn:'Changed English',version:2});
assert.equal((await anon('/public/adverts')).items.length,0,'editing requires another review');
await admin('/adverts/'+a.id+'/review','POST',{status:'rejected',reviewNote:'请补充说明',version:3});
assert.equal((await shop('/market')).adverts[0].reviewNote,'请补充说明');
await shop('/adverts/'+a.id,'PUT',{...advert,status:'draft',expiresOn:'2020-01-01',version:4});
await shop('/adverts/'+a.id,'DELETE',{version:5},409);
const avatar=await admin('/media','POST',{purpose:'avatar',data:image},201);
const c=(await admin('/data')).customers.find(c=>c.name==='注册客人');
await admin('/customers/'+c.id+'/avatar','PUT',{mediaId:avatar.id,version:c.version});
assert.equal((await admin('/data')).customers.find(x=>x.id===c.id).avatarId,avatar.id);
await anon('/public/media/'+avatar.id,'GET',undefined,404);
await guest('/logout','POST',{});await guest('/reservations','GET',undefined,401);
const mysql=await import('mysql2/promise');const db=await mysql.createConnection({host:'db',user:'neon',password:'TestDatabase123',database:'neon'});
await db.execute('DELETE FROM reservations WHERE id=?',[b.id]);await db.execute('DELETE FROM customer_accounts WHERE customer_id=?',[c.id]);await db.execute('DELETE FROM customers WHERE id=?',[c.id]);
await db.execute("UPDATE adverts SET status='published' WHERE id=?",[a.id]);assert.equal((await anon('/public/adverts')).items.length,0);await anon('/public/adverts/'+a.id,'GET',undefined,404);
await db.end();console.log('PASS: shop isolation, review, bilingual adverts, search, expiry, guest registration, reservations, private avatars and logout');
