CREATE TABLE IF NOT EXISTS users (
 id CHAR(36) PRIMARY KEY, username VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(50) NOT NULL, password_hash VARCHAR(255) NOT NULL,
 role ENUM('admin','sales') NOT NULL DEFAULT 'sales',
 enabled BOOLEAN NOT NULL DEFAULT TRUE, must_change BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL,
 expires_at DATETIME NOT NULL, INDEX(expires_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS customers (
 id CHAR(36) PRIMARY KEY, owner_id CHAR(36) NOT NULL,
 name VARCHAR(50) NOT NULL, company VARCHAR(100) NOT NULL DEFAULT '',
 phone VARCHAR(30) NOT NULL DEFAULT '', status ENUM('待联系','跟进中','已成交') NOT NULL,
 version INT NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(owner_id), FOREIGN KEY(owner_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sales (
 id CHAR(36) PRIMARY KEY, customer_id CHAR(36) NOT NULL,
 item VARCHAR(100) NOT NULL, cents BIGINT UNSIGNED NOT NULL,
 date DATE NOT NULL, version INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(customer_id), FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
