import assert from 'node:assert/strict';
const origin='http://test.local',base=process.env.TEST_API_URL||'http://127.0.0.1:3000/api';
function client(){let cookie='';return async(path,method='GET',body,status=200,source=origin)=>{
 const r=await fetch(base+path,{method,headers:{Origin:source,Cookie:cookie,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});
 if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];
 const result=await r.json();assert.equal(r.status,status,`${method} ${path}: ${JSON.stringify(result)}`);return result;
};}
const admin=client(),a=client(),b=client(),anon=client();
await anon('/data','GET',undefined,401);
await admin('/login','POST',{username:'admin',password:'TestInitial123!'},403,'https://evil.invalid');
await admin('/login','POST',{username:'admin',password:'TestInitial123!'});
await admin('/data','GET',undefined,403);
await admin('/password','POST',{oldPassword:'TestInitial123!',newPassword:'TestChanged123!'});
await admin('/data','GET',undefined,401);
await admin('/login','POST',{username:'admin',password:'TestChanged123!'});
const ua=await admin('/users','POST',{username:'seller_a',name:'销售甲',password:'SellerTemp123!'},201);
const ub=await admin('/users','POST',{username:'seller_b',name:'销售乙',password:'SellerTemp123!'},201);
for(const [c,n] of [[a,'seller_a'],[b,'seller_b']]){await c('/login','POST',{username:n,password:'SellerTemp123!'});await c('/password','POST',{oldPassword:'SellerTemp123!',newPassword:'SellerChanged123!'});await c('/login','POST',{username:n,password:'SellerChanged123!'});}
await a('/users','GET',undefined,403);
await a('/users','POST',{username:'intruder',name:'侵入',password:'Password12345'},403);
const customer={name:'<script>客户甲</script>',company:'测试公司',phone:'13800000000',status:'跟进中',ownerId:ub.id};
const ca=await a('/customers','POST',customer,201);
assert.equal((await a('/data')).customers[0].ownerId,ua.id,'seller cannot assign to another owner');
assert.equal((await b('/data')).customers.length,0,'other seller cannot read customer');
await b('/customers/'+ca.id,'PUT',{...customer,version:1},404);
await b('/sales','POST',{customerId:ca.id,item:'越权',cents:100,date:'2026-09-03'},404);
const sale={customerId:ca.id,item:'演示服务',cents:12345,date:'2026-09-03'};
await a('/sales','POST',{...sale,date:'2026-02-31'},400);
await a('/sales','POST',{...sale,cents:-1},400);
const sa=await a('/sales','POST',sale,201);
await b('/sales/'+sa.id,'DELETE',{version:1},404);
await a('/customers/'+ca.id,'DELETE',{version:1},409);
await a('/customers/'+ca.id,'PUT',{...customer,name:'更新客户',version:1});
await a('/customers/'+ca.id,'PUT',{...customer,version:1},409);
assert.equal((await admin('/data')).sales[0].cents,12345);
await admin('/customers/'+ca.id,'PUT',{...customer,ownerId:ub.id,version:2});
assert.equal((await a('/data')).sales.length,0,'transfer revokes old owner sales access');
assert.equal((await b('/data')).sales.length,1);
await admin('/users/'+ub.id,'PATCH',{name:'销售乙',enabled:false});
await b('/data','GET',undefined,401);
await b('/login','POST',{username:'seller_b',password:'SellerChanged123!'},401);
await admin('/users/'+ub.id,'PATCH',{name:'销售乙',enabled:true,password:'ResetTemporary123!'});
await b('/login','POST',{username:'seller_b',password:'SellerChanged123!'},401);
await b('/login','POST',{username:'seller_b',password:'ResetTemporary123!'});
await b('/data','GET',undefined,403);
await admin('/sales/'+sa.id,'DELETE',{version:1});
await admin('/customers/'+ca.id,'DELETE',{version:3});
await admin('/customers','POST',{...customer,name:'持久化验收',ownerId:ua.id},201);
await admin('/logout','POST',{});
await admin('/me','GET',undefined,401);
console.log('PASS: authentication, CSRF, forced password change, roles, ownership, CRUD, versions, amount/date validation, transfer, disable/reset, logout.');
