import './manage.css';
import {cropImage} from './media-picker.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={customers:'客户管理',sales:'销售记录',users:'账号管理',shops:'店铺管理',adverts:'业务广告',reservations:'预约与留言',categories:'广告分类'};
const roles={admin:'管理员',sales:'销售员',shop:'店铺管理员',customer:'客人'};
const statuses={draft:'草稿',pending:'待审核',published:'已发布',offline:'已下架',rejected:'审核未通过',confirmed:'已确认',completed:'已完成',cancelled:'已取消'};
const categoryLabel=id=>{const c=data.categories.find(c=>c.id===id);return c?c.name+' / '+c.nameEn:id;};
let saleChoices={shops:[],adverts:[]};
let user=null,data={customers:[],sales:[],users:[],shops:[],adverts:[],reservations:[],categories:[]},view='customers',editing=null,mode='',media=[],avatar=null,avatarChanged=false,uploading=false;
const editor=$('editor'),deletion=$('delete-dialog'),passwordDialog=$('password-dialog');
function loggedOut(){user=null;for(const key of Object.keys(data))data[key]=[];document.querySelectorAll('dialog').forEach(d=>d.close());$('workspace').hidden=true;$('auth-gate').hidden=false;$('table-body').innerHTML='';$('fields').innerHTML='';}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json().catch(()=>({error:'服务器连接异常，请重试。'}));if(!r.ok){if(r.status===401&&path!=='/login')loggedOut();throw new Error(result.error||'操作失败');}return result;}
async function busy(form,fn,error='form-error'){const buttons=form.querySelectorAll('button[type=submit]');buttons.forEach(b=>b.disabled=true);$(error).textContent='';try{await fn();}catch(e){$(error).textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
function passwordForm(){ $('password-form').reset();$('password-error').textContent='';$('password-note').textContent=user?.mustChange?'首次登录请修改临时密码，完成后重新登录。':'修改后所有设备将退出登录。';$('password-cancel').hidden=!!user?.mustChange;passwordDialog.showModal();}
async function enter(){if(user.role==='customer'){await api('/logout','POST',{});loggedOut();throw new Error('这是店铺和员工管理站，客人请在展示网站登录。');}$('auth-gate').hidden=true;$('workspace').hidden=false;$('identity').textContent=`${user.name} · ${roles[user.role]}`;view=user.role==='shop'?'shops':'customers';document.querySelectorAll('[data-view]').forEach(b=>{b.hidden=!(user.role==='admin'||(user.role==='shop'?['shops','adverts','reservations','sales'].includes(b.dataset.view):['customers','sales','reservations'].includes(b.dataset.view)));if(b.dataset.view==='sales')b.textContent=user.role==='shop'?'成交记录':'销售记录';});$('stats').hidden=user.role==='shop';if(user.mustChange){passwordForm();return;}await refresh();}
async function refresh(){if(user.role!=='shop')Object.assign(data,await api('/data'));else data.sales=await api('/shop-sales');if(user.role==='admin')data.users=await api('/users');if(user.role!=='sales')Object.assign(data,await api('/market'));data.categories=await api('/categories');if(user.role!=='shop')saleChoices=await api('/sale-options');data.reservations=await api('/reservations');render();}
const money=n=>(n/100).toLocaleString('zh-CN',{style:'currency',currency:'CNY'});
const cells=items=>items.map(s=>`<td>${esc(s)}</td>`).join('');
const action=(kind,id,label)=>`<button data-action="${kind}" data-id="${esc(id)}">${label}</button>`;
const actions=(r,remove=true)=>`<td>${action('edit',r.id,'编辑')}${remove?action('delete',r.id,'删除'):''}</td>`;
const expired=a=>a.expiresOn&&a.expiresOn<new Date(Date.now()+8*3600000).toISOString().slice(0,10);
function render(){
 $('customer-count').textContent=data.customers.length;$('sale-count').textContent=data.sales.length;$('sale-total').textContent=money(data.sales.reduce((n,s)=>n+s.cents,0));$('section-title').textContent=view==='sales'&&user.role==='shop'?'成交记录':labels[view];$('add').textContent=view==='shops'&&user.role==='shop'?'我要开店':'新增'+({customers:'客户',sales:'销售',users:'账号',shops:'店铺',adverts:'广告',categories:'分类'}[view]||'');$('add').hidden=view==='reservations'||(view==='sales'&&user.role==='shop')||(view==='shops'&&(user.role==='admin'||data.shops.length>0));$('search').placeholder='搜索当前列表…';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',view===b.dataset.view));
 const q=$('search').value.trim().toLowerCase();let rows=data[view].filter(r=>JSON.stringify(r).toLowerCase().includes(q)),headers,html;
 if(view==='customers'){headers=['客户','公司','电话','状态','负责人','操作'];html=rows.map(c=>`<tr><td><span class="customer-cell">${c.avatarId?`<img class="avatar" alt="${esc(c.name)}头像" src="/api/media/${esc(c.avatarId)}">`:`<span class="avatar avatar-placeholder">${esc(c.name.slice(0,1))}</span>`}${esc(c.name)}</span></td>${cells([c.company||'—',c.phone||'—',c.status,c.ownerName])}${actions(c)}</tr>`);}
 else if(view==='sales'){headers=['客户','销售项目','店铺 / 广告','金额','日期','来源','操作'];html=rows.map(s=>`<tr>${cells([s.customerName||data.customers.find(c=>c.id===s.customerId)?.name||'未知客户',s.item,[s.shopName,s.advertTitle].filter(Boolean).join(' / ')||'未关联',money(s.cents),s.date,s.reservationId?'预约成交':'手动录入'])}${user.role==='shop'?'<td>—</td>':actions(s)}</tr>`);}
 else if(view==='users'){headers=['账号','姓名','角色','状态','操作'];html=rows.map(u=>`<tr>${cells([u.username,u.name,roles[u.role],u.enabled?'正常':'停用'])}${u.role==='admin'||u.role==='customer'?'<td>—</td>':actions(u,false)}</tr>`);}
 else if(view==='shops'){headers=['店铺名称','英文名称','负责人','联系电话','状态','操作'];html=rows.map(s=>`<tr>${cells([s.name,s.nameEn||'—',s.ownerName,s.phone||'—',s.enabled?'正常':'已停用'])}${actions(s,user.role==='admin')}</tr>`);}
 else if(view==='categories'){headers=['中文名称','英文名称','排序（小值在前）','操作'];html=rows.map(c=>`<tr>${cells([c.name,c.nameEn,c.sortOrder])}${actions(c)}</tr>`);}
 else if(view==='adverts'){headers=['广告','店铺 / 分类','发布状态','到期日（北京时间）','操作'];html=rows.map(a=>`<tr><td><div class="customer-cell">${a.images[0]?`<img class="ad-thumb" alt="广告封面" src="/api/media/${esc(a.images[0])}">`:''}<span>${esc(a.title)}<small class="subline">${esc(a.titleEn)}</small></span></div></td><td>${esc(a.shopName)}<small class="subline">${esc(categoryLabel(a.category))}</small></td><td><span class="badge ${a.status}">${expired(a)?'已过期':statuses[a.status]}</span>${a.pinned?' · 置顶':''}<small class="subline">${esc(a.reviewNote)}</small></td>${cells([a.expiresOn||'长期有效'])}<td>${action('edit',a.id,'编辑')}${user.role==='admin'&&a.status==='pending'?action('review',a.id,'审核'):''}${user.role==='admin'&&a.status==='published'?action('pin',a.id,a.pinned?'取消置顶':'置顶'):''}${action('delete',a.id,'删除')}</td></tr>`);}
 else {headers=['客人','广告 / 店铺','预约时间','留言 / 回复','状态','操作'];html=rows.map(r=>`<tr>${cells([r.customerName+' / '+r.phone])}<td>${esc(r.title)}<small class="subline">${esc(r.shopName)}</small></td>${cells([new Date(r.requestedAt.replace(' ','T')+'Z').toLocaleString('zh-CN')])}<td class="message-cell">${esc(r.message)}<small class="subline">${esc(r.reply||'暂无回复')}</small></td><td>${r.status==='pending'?'待确认':statuses[r.status]}</td><td>${['admin','shop'].includes(user.role)&&['pending','confirmed'].includes(r.status)?action('reservation',r.id,'处理预约'):''}${r.saleId?'<span class="badge">已转销售</span>':['confirmed','completed'].includes(r.status)&&['admin','sales','shop'].includes(user.role)?action('convert',r.id,user.role==='shop'?'确认成交':'登记成交'):''}</td></tr>`);}
 $('table-head').innerHTML='<tr>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr>';$('table-body').innerHTML=html.join('');$('empty').hidden=rows.length>0;$('empty').textContent=q?'没有匹配的记录。':view==='shops'&&user.role==='shop'?'欢迎！点击“我要开店”填写店铺资料，完成后即可提交业务广告。':view==='shops'&&user.role==='admin'?'暂无店铺。请先在“账号管理”创建店铺管理员账号，由店主登录后自行开店。':view==='sales'&&user.role==='shop'?'暂无成交。预约确认成交后会显示在这里。':view==='reservations'?'暂无预约，客人在前台提交后会出现在这里。':'暂无记录，点击新增开始。';
}
const field=(name,label,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
const area=(name,label,value='',max=4000)=>`<label>${label}<textarea name="${name}" rows="4" maxlength="${max}">${esc(value)}</textarea></label>`;
const select=(name,label,choices,value)=>`<label>${label}<select name="${name}">${choices.map(([v,t])=>`<option value="${esc(v)}"${String(v)===String(value)?' selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function mediaUI(){return `<div class="media-block"><label>广告图片（第一张为封面，最多 6 张）<input id="ad-file" type="file" accept="image/jpeg,image/png,image/webp"></label><div id="media-preview" class="media-preview"></div><p class="storage-note">选择图片后可拖动、缩放裁剪；每张图片压缩后上传。</p></div>`;}
function previews(){const target=$('media-preview');if(target)target.innerHTML=media.map((id,i)=>`<figure><img src="/api/media/${esc(id)}" alt="图片 ${i+1}"><button type="button" data-remove-image="${i}">移除</button>${i?`<button type="button" data-cover="${i}">设为封面</button>`:'<small>封面</small>'}</figure>`).join('');const img=$('avatar-preview');if(img)img.innerHTML=avatar?`<img class="avatar large" src="/api/media/${esc(avatar)}" alt="客户头像">`:'未设置头像';}
function bindUploads(){previews();const bind=(id,purpose,square)=>{const input=$(id);if(input)input.onchange=async()=>{const file=input.files[0];if(!file)return;input.value='';if(purpose==='advert'&&media.length>=6){$('form-error').textContent='最多上传 6 张图片。';return;}uploading=true;$('save-record').disabled=true;try{const image=await cropImage(file,square);if(image){const r=await api('/media','POST',{purpose,data:image});if(square){avatar=r.id;avatarChanged=true;}else media.push(r.id);previews();}}catch(e){$('form-error').textContent=e.message;}finally{uploading=false;$('save-record').disabled=false;}};};bind('ad-file','advert',false);bind('avatar-file','avatar',true);if($('remove-avatar'))$('remove-avatar').onclick=()=>{avatar=null;avatarChanged=true;previews();};}
function saleFields(r){return field('item','销售项目 *',r?.item,'required maxlength="100"')+field('amount','实际成交金额（元）*',r?.cents?(r.cents/100).toFixed(2):'','required type="number" step="0.01" min="0.01" max="999999999"')+field('date','销售日期 *',r?.date||new Date().toLocaleDateString('sv-SE'),'required type="date" min="2000-01-01" max="2100-12-31"');}
function adOptions(shopId){return [['','不关联广告'],...saleChoices.adverts.filter(a=>a.shopId===shopId).map(a=>[a.id,a.title])];}
function saleLinks(r){const shops=[['','不关联店铺'],...saleChoices.shops.map(s=>[s.id,s.name])];if(r?.shopId&&!shops.some(([id])=>id===r.shopId))shops.push([r.shopId,r.shopName+'（历史关联）']);const ads=adOptions(r?.shopId);if(r?.advertId&&!ads.some(([id])=>id===r.advertId))ads.push([r.advertId,r.advertTitle+'（历史关联）']);return select('shopId','店铺（可选）',shops,r?.shopId)+select('advertId','广告（可选，先选择店铺）',ads,r?.advertId);}
function openEditor(id=null,special=''){
 editing=id;mode=special;avatarChanged=false;uploading=false;$('save-record').disabled=false;$('form-error').textContent='';const r=data[view].find(r=>r.id===id);$('dialog-title').textContent=special==='review'?'审核广告':special==='reservation'?'处理预约':special==='convert'?'预约转销售':(id?'编辑':'新增')+({customers:'客户',sales:'销售记录',users:'账号',shops:'店铺',adverts:'广告',categories:'分类'}[view]||labels[view]);let html='';
 if(special==='review'){html=`<h3>${esc(r.title)}</h3><p>${esc(r.titleEn)}</p><div class="review-copy">${esc(r.body)}</div><div class="review-copy">${esc(r.bodyEn)}</div><div class="media-preview">${r.images.map(id=>`<img src="/api/media/${esc(id)}" alt="待审核广告图片">`).join('')}</div>`+select('status','审核决定',[['published','审核通过并发布'],['rejected','不通过']], 'published')+area('reviewNote','审核说明（不通过时必填）','',500)+select('pinned','是否置顶',[['false','普通展示'],['true','置顶展示']],String(!!r.pinned));}
 else if(special==='reservation'){html=`<h3>${esc(r.customerName)} · ${esc(r.phone)}</h3><p class="review-copy">${esc(r.message)}</p>`+select('status','处理结果',r.status==='pending'?[['confirmed','确认预约'],['cancelled','取消预约']]:[['completed','已完成'],['cancelled','取消预约']],r.status==='pending'?'confirmed':'completed')+area('reply','回复客人',r.reply,2000);}
 else if(special==='convert'){html=`<p class="storage-note">${user.role==='shop'?'确认成交后将完成预约，并生成关联客人、店铺和广告的成交记录。':'确认实际成交后录入金额；同一预约只能关联一笔销售。'}</p><p>${esc(r.customerName)} · ${esc(r.shopName)}</p><p>${esc(r.title)}</p>`+saleFields({item:r.title.slice(0,100)});}
 else if(view==='categories'){html=field('name','中文名称 *',r?.name,'required maxlength="60"')+field('nameEn','英文名称 *',r?.nameEn,'required maxlength="100"')+field('sortOrder','排序值（越小越靠前）',r?.sortOrder??0,'required type="number" min="0" max="9999" step="1"')+'<p class="storage-note">改名会同步更新前台和店铺发布表单。已被广告使用的分类不能删除。</p>';}
 else if(view==='customers'){avatar=r?.avatarId||null;html=`<div class="avatar-edit"><div id="avatar-preview"></div><label>客户头像<input id="avatar-file" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" id="remove-avatar">移除头像</button></div>`+field('name','客户姓名 *',r?.name,'required maxlength="50"')+field('company','公司',r?.company,'maxlength="100"')+field('phone','联系电话',r?.phone,'maxlength="30"')+select('status','跟进状态',['待联系','跟进中','已成交'].map(v=>[v,v]),r?.status)+(user.role==='admin'?select('ownerId','负责人',data.users.filter(u=>['admin','sales'].includes(u.role)&&u.enabled).map(u=>[u.id,u.name]),r?.ownerId||user.id):'');}
 else if(view==='sales'){if(!data.customers.length){$('notice').textContent='请先添加客户。';return;}html=r?.reservationId?'<p class="storage-note">来自预约，客人、店铺和广告不可更换；金额、项目和日期可更正。</p><p>'+esc(data.customers.find(c=>c.id===r.customerId)?.name)+' · '+esc(r.shopName)+' · '+esc(r.advertTitle)+'</p>':select('customerId','客户 *',data.customers.map(c=>[c.id,c.name]),r?.customerId)+saleLinks(r);html+=saleFields(r);}
 else if(view==='users'){html=field('username','登录账号 *',r?.username,id?'disabled':'required minlength="3" maxlength="40"')+field('name','姓名 *',r?.name,'required maxlength="50"')+field('password',id?'重置临时密码（留空不变）':'临时密码 *','','type="password" minlength="10" maxlength="128" autocomplete="new-password" '+(id?'':'required'))+(id?select('enabled','状态',[['true','正常'],['false','停用']],String(r.enabled)):select('role','账号类型',[['shop','店铺管理员（自行开店）'],['sales','销售员（客户与销售管理）']],'shop'))+'<p class="storage-note">客人在展示站自行注册；此处创建员工和店铺账号。临时密码首次登录必须修改。</p>';}
 else if(view==='shops'){const owners=data.users.filter(u=>u.role==='shop'&&u.enabled).map(u=>[u.id,u.name+' / 店铺管理员']);if(user.role==='admin'&&r&&!owners.some(([id])=>id===r.ownerId))owners.push([r.ownerId,r.ownerName+' / 历史负责人（建议改派）']);html='<p class="storage-note">店铺管理员使用平台分配的账号登录，并自行录入一家店铺。平台管理员只维护已有店铺和调整负责人。</p>'+field('name','店铺中文名称 *',r?.name,'required maxlength="80"')+field('nameEn','店铺英文名称',r?.nameEn,'maxlength="120"')+area('description','中文介绍',r?.description)+area('descriptionEn','英文介绍',r?.descriptionEn)+field('phone','联系电话',r?.phone,'maxlength="40"')+field('wechat','微信',r?.wechat,'maxlength="80"')+field('address','地址',r?.address,'maxlength="200"')+(user.role==='admin'?select('ownerId','店铺负责人（必须是店铺管理员账号）',owners,r?.ownerId)+select('enabled','店铺状态',[['true','正常'],['false','停用（广告隐藏）']],String(r?!!r.enabled:true)):'');}
 else if(view==='adverts'){if(!data.categories.length){$('notice').textContent='请联系管理员先创建广告分类。';return;}if(!data.shops.filter(s=>s.enabled).length){$('notice').textContent='请先创建或启用店铺，再发布广告。';return;}media=r?[...r.images]:[];html=select('shopId','所属店铺 *',data.shops.filter(s=>s.enabled).map(s=>[s.id,s.name]),r?.shopId)+field('title','广告中文标题 *',r?.title,'required maxlength="120"')+field('titleEn','广告英文标题（提交审核必填）',r?.titleEn,'maxlength="160"')+area('body','中文图文详情 *',r?.body,12000)+area('bodyEn','英文图文详情（提交审核必填）',r?.bodyEn,12000)+select('category','分类',data.categories.map(c=>[c.id,categoryLabel(c.id)]),r?.category||data.categories[0]?.id)+mediaUI()+field('expiresOn','到期日期（北京时间当日结束后自动下架，留空为长期）',r?.expiresOn,'type="date"')+select('status','保存方式',[['draft','保存草稿'],['pending','提交管理员审核'],['offline','下架']],r?.status==='offline'?'offline':'draft')+'<p class="storage-note">图文详情采用文字和图片组合。审核通过后才公开；编辑已发布广告需重新审核。</p>';}
 $('fields').innerHTML=html;editor.showModal();bindUploads();const shopSelect=$('fields').querySelector('[name=shopId]');if(view==='sales'&&shopSelect)shopSelect.onchange=()=>{const ads=$('fields').querySelector('[name=advertId]');ads.innerHTML=adOptions(shopSelect.value).map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');};
}
$('record-form').onsubmit=e=>{e.preventDefault();if(uploading)return;void busy(e.currentTarget,async()=>{const f=new FormData(e.currentTarget),get=k=>String(f.get(k)||'').trim(),r=data[view].find(r=>r.id===editing);let body,endpoint='/'+view+(editing?'/'+editing:''),method=editing?(view==='users'?'PATCH':'PUT'):'POST';
 if(mode==='review'){endpoint='/adverts/'+editing+'/review';method='POST';body={status:get('status'),reviewNote:get('reviewNote'),pinned:get('pinned')==='true',version:r.version};}
 else if(mode==='reservation'){endpoint='/reservations/'+editing;method='PATCH';body={status:get('status'),reply:get('reply'),version:r.version};}
 else if(mode==='convert'){endpoint=user.role==='shop'?'/reservations/'+editing+'/sale':'/sales';method='POST';body={customerId:r.customerId,reservationId:r.id,reservationVersion:r.version,item:get('item'),cents:Math.round(Number(get('amount'))*100),date:get('date')};}
 else if(view==='categories')body={name:get('name'),nameEn:get('nameEn'),sortOrder:Number(get('sortOrder')),version:r?.version};
 else if(view==='customers')body={name:get('name'),company:get('company'),phone:get('phone'),status:get('status'),ownerId:user.role==='admin'?get('ownerId'):user.id,version:r?.version};
 else if(view==='sales')body={customerId:r?.reservationId?r.customerId:get('customerId'),shopId:r?.reservationId?r.shopId:get('shopId'),advertId:r?.reservationId?r.advertId:get('advertId'),reservationId:r?.reservationId,item:get('item'),cents:Math.round(Number(get('amount'))*100),date:get('date'),version:r?.version};
 else if(view==='users')body={username:get('username'),name:get('name'),password:String(f.get('password')||''),role:get('role'),enabled:get('enabled')==='true'};
 else if(view==='shops')body={...Object.fromEntries(f),enabled:get('enabled')==='true',version:r?.version};
 else body={...Object.fromEntries(f),images:media,version:r?.version};
 const saved=await api(endpoint,method,body);
 if(view==='customers'&&avatarChanged){editing=saved.id;await refresh();const row=data.customers.find(c=>c.id===editing);await api('/customers/'+editing+'/avatar','PUT',{mediaId:avatar,version:row.version});}
 editor.close();await refresh();$('notice').textContent=mode==='review'?'审核结果已保存。':mode==='convert'?'成交已登记，可在销售记录中查看。':'已保存到服务器。';
 });};
$('fields').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.removeImage!==undefined){media.splice(+b.dataset.removeImage,1);previews();}if(b?.dataset.cover!==undefined){media.unshift(media.splice(+b.dataset.cover,1)[0]);previews();}};
$('table-body').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const r=data[view].find(r=>r.id===b.dataset.id);if(!r)return;const kind=b.dataset.action;if(kind==='edit'||kind==='review'||kind==='reservation'||kind==='convert')openEditor(r.id,kind==='edit'?'':kind);else if(kind==='pin')void busy($('workspace'),async()=>{await api('/adverts/'+r.id+'/pin','PATCH',{pinned:!r.pinned,version:r.version});await refresh();},'notice');else if(kind==='delete'){$('delete-prompt').textContent='确认删除这条记录？有关联记录时不能删除，可选择停用或下架。';$('delete-error').textContent='';deletion.showModal();$('delete-confirm').onclick=()=>void busy(deletion,async()=>{await api('/'+view+'/'+r.id,'DELETE',{version:r.version});deletion.close();await refresh();},'delete-error');}};
$('login-form').onsubmit=e=>{e.preventDefault();void busy(e.currentTarget,async()=>{user=(await api('/login','POST',Object.fromEntries(new FormData(e.currentTarget)))).user;$('login-form').reset();await enter();},'login-error');};
$('logout').onclick=async()=>{const b=$('logout');b.disabled=true;try{await api('/logout','POST',{});loggedOut();$('login-error').textContent='已安全退出登录。';}catch(e){$('notice').textContent=e.message;}finally{b.disabled=false;}};
$('change-password').onclick=passwordForm;passwordDialog.oncancel=e=>{if(user?.mustChange)e.preventDefault();};$('password-cancel').onclick=()=>passwordDialog.close();$('password-form').onsubmit=e=>{e.preventDefault();void busy(e.currentTarget,async()=>{const f=new FormData(e.currentTarget);if(f.get('newPassword')!==f.get('confirmPassword'))throw new Error('两次新密码不一致。');await api('/password','POST',{oldPassword:f.get('oldPassword'),newPassword:f.get('newPassword')});loggedOut();$('login-error').textContent='密码已更新，请重新登录。';},'password-error');};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$('search').value='';$('notice').textContent='';render();});$('refresh').onclick=()=>void busy($('workspace'),refresh,'notice');$('search').oninput=render;$('add').onclick=()=>openEditor();$('close').onclick=$('cancel').onclick=()=>editor.close();$('delete-cancel').onclick=()=>deletion.close();
api('/me').then(async r=>{user=r.user;await enter();}).catch(e=>{loggedOut();if(!e.message.includes('登录'))$('login-error').textContent=e.message;});
